# Generate protobuf JSON descriptor from .proto files
# This allows embedding protobuf definitions in the compiled binary

Write-Host "[proto-generator] Generating protobuf JSON descriptor..."

$rootDir = $PSScriptRoot | Split-Path
$protoDir = Join-Path $rootDir "external/nicolive-comment-protobuf/proto"
$outputJson = Join-Path $rootDir "src/services/nicolive-proto.json"
$outputTs = Join-Path $rootDir "src/services/nicolive-proto.ts"

if (-not (Test-Path $protoDir)) {
    Write-Error "Proto directory not found: $protoDir"
    exit 1
}

# Use pbjs from protobufjs package to generate JSON descriptor
# This resolves all imports including google.protobuf.* types
$mainProto = "dwango/nicolive/chat/service/edge/payload.proto"

Write-Host "[proto-generator] Converting $mainProto to JSON..."
Write-Host "[proto-generator] Output file: $outputJson"

# Change to proto directory and run pbjs
Push-Location $protoDir
try {
    # Run pbjs to generate static JSON module
    $json = npx -y protobufjs-cli pbjs -t json $mainProto
    
    if ($LASTEXITCODE -eq 0) {
        $json | Out-File -Encoding UTF8 $outputJson
        # Also write a TypeScript module that exports the descriptor as default
        $ts = "/* GENERATED FILE - DO NOT EDIT */`n// Auto-generated by scripts/generate-proto-descriptor.ps1`nconst descriptor = $json as const;`nexport default descriptor;`n"
        $ts | Out-File -Encoding UTF8 $outputTs
        Write-Host "[proto-generator] Successfully generated protobuf descriptor"
        $size = (Get-Item $outputJson).Length / 1KB
        Write-Host "[proto-generator] File size: $([math]::Round($size, 2)) KB"
    } else {
        Write-Error "[proto-generator] Failed to generate protobuf descriptor"
        exit 1
    }
} finally {
    Pop-Location
}
