// Generate protobuf JSON descriptor
import protobuf from "protobufjs";
import { join } from "@std/path";

const PROTO_DIR = join(Deno.cwd(), "external", "nicolive-comment-protobuf", "proto");
const OUTPUT_JSON = join(Deno.cwd(), "src", "services", "nicolive-proto.json");
const OUTPUT_TS = join(Deno.cwd(), "src", "services", "nicolive-proto.ts");

console.log("[proto-generator] Generating protobuf JSON descriptor...");
console.log("[proto-generator] Proto dir:", PROTO_DIR);
console.log("[proto-generator] Output file:", OUTPUT_JSON);

try {
    const payloadPath = join(PROTO_DIR, "dwango/nicolive/chat/service/edge/payload.proto");

    const root = new protobuf.Root();
    root.resolvePath = (_origin: string, target: string) => {
        // Prefer local proto directory if target exists there
        try {
            const candidate = join(PROTO_DIR, target);
            // Deno.statSync will throw if not exists
            Deno.lstatSync(candidate);
            return candidate;
        } catch (_err) {
            // Fallback to default resolution: return target so protobufjs can try builtin includes
            return target;
        }
    };

    await root.load([payloadPath], { keepCase: true });

    const descriptor = root.toJSON();
    const json = JSON.stringify(descriptor, null, 2);
    await Deno.writeTextFile(OUTPUT_JSON, json);

    // Also output a TypeScript module that exports the descriptor as default.
    const tsModule = `/* GENERATED FILE - DO NOT EDIT */\n// Auto-generated by scripts/generate-proto-descriptor.ts\nconst descriptor = ${json} as const;\nexport default descriptor;\n`;
    await Deno.writeTextFile(OUTPUT_TS, tsModule);

    const size = json.length / 1024;
    console.log(`[proto-generator] Successfully generated (${size.toFixed(2)} KB)`);
} catch (error) {
    console.error("[proto-generator] Failed:", error);
    Deno.exit(1);
}
